services:
  - type: web
    name: netsapiens-joy-interface
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: NITRO_HOST=0.0.0.0 NITRO_PORT=$PORT node .output/server/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
